print("   Date personale")
print("Cabac Alexandru")
print("str. Independenței 100/36 cod poștal 3100 Moldova")
print("Mobil: +37379008101")
print("E-mail: alexandru.cabac@gmail.com")
print("Naționalitate: Moldovean")
print("Sex: Masculin")
print("   Educație și formare:")
print("Perioada 2020-prezent")
print("Învăț la profil real la I.P.L.T.'Mihai Eminescu'")
print("Perioada 2015-2020")
print("Absolvirea gimnaziului I.P.L.T.'Mihai Eminescu'")
print("Perioada 2011-2015")
print("Absolvirea școlii primare I.P.L.T'Mihai Eminescu'")
print("   Aptitudini și competențe personale")
print("Limba maternă Română")
print("Limba străine cunoscute, Autoevaluare")
print("                                                       Vorbire                 Scriere")
print("             |Ascultare| Citire| Participare la conversație| Discurs Oral| Exprimare scrisă|")
print("Limba Germană| A2      |    A2 |      A2                   |   A2        |      A2         |")
print("Limba Engleză| B2      |    B2 |      B1                   |   B1        |      B1         |")
print("Competențe și abilități sociale: Spirit de echipă, dezvoltat într-o anumită masură")
print("de jocul de volei, participarea la concursuri de robotică în echipe și")
print("participării la dezbateri organizate la U.S.'Alecu Russo'")
print("Competențe și aptitudini de utilizare a calculatorului: Pot folosi limbajul de programare C++")
print("Competențe și aptitudini artistice: Percuția")
print("Hobby: Volei, mersul cu bicicleta, percuția și colecționatul monedelor")